

try {
    let x = y + 2;
} catch (error) {
    console.log("Error: " + error.message);
}